<?php
/**
 * Uninstall
 *
 * Implements hook_uninstall()
 */
function wl_editing_framework_uninstall() {
  variable_del('wl_editing_framework_allowed_layouts');
}

/**
 * Enable the base theme
 *
 * Implements hook_enable()
 */
function wl_editing_framework_enable() {
  variable_set('page_manager_node_view_disabled', 0);
  menu_rebuild();

  theme_enable(array('wl'));
  variable_set('theme_default', 'wl');
}